sudo: required
services:
  - docker
before_install:
  - docker build -t seshadri/react -f Dockerfile.dev .

script:
  - docker run -e CI=true seshadri/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-026164424685"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
